### ISSUE TITLE
Clarify build instructions

### ISSUE THREAD

**Issue by wrouesnel** [freelan-developers/freelan-all#32]
The build instructions need to be clarified that on Linux-y systems it's totally unnecessary to do the `teapot build` phase of things, and also currently impossible (no teapot build filters in the party file).

What is needed is a list of apt packages to install on various distros.

For Ubuntu/Debian/Mint the list seems to be:
```
apt-get install libboost-dev-all libcurl4-openssl-dev
```

so far. I plan to get started on spinning up some apt packages soon so I suspect I'll find more.

**Comment by CristianCantoro** [comment]
I may add that some information about the minimun required version for build tools and library can be helpful. I have installed the current master (https://github.com/freelan-developers/freelan-all/commit/30dd3972f5804d1d81d92fbc26f39a0231e6110f) on an Ubuntu 14.10 laptop (see [freelan.debian issue #1](https://github.com/freelan-developers/freelan.debian/issues/1)) and I wanted to install it also an another machine with [ElementaryOS](http://elementary.io/) Luna, which is based on Ubuntu 12.04 LTS.
To install it I had to:
* upgrade the `g++` version, because the default `g++-4.6` does not handle the `--std=c++11` option. I am using `g++-4.9` now and precisely `g++ (Ubuntu 4.9.2-0ubuntu1~12.04) 4.9.2`
* upgrade `libbost` from the default `v. 1.46`. I am using `v.1.55` now)

 Hope this helps.

**Comment by ereOn** [comment]
@CristianCantoro Indeed, it makes sense to be accurate regarding the versions.

Thanks for the feedback !

**Comment by ereOn** [comment]
Just for reference #50 took care of some of the concerns here.

**Comment by ereOn** [comment]
#56 Added a `README.linux` file that also gives additional instructions.
