### ISSUE TITLE
Support OpenSSL PSK ciphersuites

### ISSUE THREAD

**Issue by wrouesnel** [freelan-developers/freelan-all#34]
The requirement to setup X509 certificates is fairly burdensome for users - OpenSSL includes support for pre-shared key ciphersuites out of the box (don't know if the C++ wrapper in Freelan does though).

It would be great to support setting a pre-shared key in the freelan2.cfg file, to use the VPN in a "group password" mode (similar to Hamachi) and a much more comprehensible use-case for users.

**Comment by ereOn** [comment]
This is now implemented and functional.

There are a few new configuration options, the most interesting one being :

`security.passphrase` which takes an arbitrary string from which a pre-shared key is derived using PBKDF2 (configurable salt and iterations count). This PSK is used instead of the certificates to sign and verify `SESSION` and `SESSION_REQUEST` messages with a HMAC-SHA256.

The client can support both PSK and RSA mode at the same time for hybrid networks.

The `PRESENTATION` messages format changed to allow for empty certificates (which means that a pre-shared key is being used by the host).

The RFC was updated as well to reflect the protocol changes.

I wanted this for a long time, and now it's real ! Enjoy !

**Comment by leggewie** [comment]
Awesome, thank you!
