### ISSUE TITLE
"scons all" only installs the freelan2 binary

### ISSUE THREAD

**Issue by leggewie** [freelan-developers/freelan-all#59]
Did my first successful compilations, but scons does not seem to install anything much.

$ find install/ -type f
install/bin/freelan2

Is that really all?

**Comment by ereOn** [comment]
The installation target is platform agnostic. It only copies the generated binaries (and it happens that there is only one).

I guess we could extend that to copy the configuration files as well.

**Comment by ereOn** [comment]
@leggewie : The more I think of this, the more it seems to me that installing the configuration file is the responsibility of the packaging system/installer system, not the build system.

After all, the configuration files are not an artifact of the build system.

Do you see any reason why this should be done ?

**Comment by leggewie** [comment]
well, it seems to be standard practice. let me ask you back: "why bother with an install command at all if it's the responsability of the packager?"

**Comment by ereOn** [comment]
@leggewie 

The main issue I have with that is that the installation phase takes a `prefix` but this doesn't work for Debian :

> scons install prefix=/usr/local

Where should the configuration file go ? Usually configuration files go to `/etc/` but with the specified prefix, we are out of luck. Or is it acceptable to have the configuration file in say `/usr/local/etc/` ? I would then need to change freelan's configuration file discovery to account for these cases (not a problem, I just say that as a reminder).

If you think this is acceptable, I'll change the installation phase this week-end.

**Comment by leggewie** [comment]
Sure that is acceptable.  I maintain scanbd in Debian and that is how their default is.  Obviously, for Debian I change that from /usr/local to /

**Comment by ereOn** [comment]
@leggewie Good ! How do you "change" that ? Patch ? Compilation flag ?

What would be your preference ?

**Comment by ereOn** [comment]
@leggewie : I pushed to the `configuration_as_build_artifact` branch, the changes you requested.

Could you please let me know if that seems okay to you ?

Basically, here is what changed:

* Calling `scons install prefix=/usr/local` creates both `/usr/local/bin/freelan2` and `/usr/local/etc/freelan/freelan.cfg`
* On Windows, the `etc/freelan/` part of the path is `config/` instead.
* The installation path is hardcoded in the binary (via a compilation flag generated for you automatically) : this installation path becomes the default (but you can obviously still use `-c some/path/config.cfg` to specify another one).

I believe those changes should ease the packaging phase, but I may have missed some things so please let me know :)

**Comment by leggewie** [comment]
I haven't tested this yet.  I believe there are other files that should be shipped as well.  But I guess they can be added later as necessary now that the plumbing seems to be in place.

Where is the default installation location? /usr/local? ./install/ as previously?  I'm sorry, but I can't grok the change you made at this time of day.  Good night.

**Comment by ereOn** [comment]
The "default" is indeed `./install` because that's convenient when testing. I'd like to leave it that way if possible.

I assume it's not a problem since the packaing `Makefile` can just specify `prefix=/` instead.

**Comment by leggewie** [comment]
"The installation path is hardcoded in the binary (via a compilation flag generated for you automatically)" Is that a relative or an absolute path?  I don't think either will work, in fact.  Debian often builds in a chroot, so the relative installation path would be debian/freelan/, for example, installing to debian/freelan/{etc,usr/sbin}.  The binary package will then be installing to /etc and /usr

**Comment by leggewie** [comment]
seems like the hardcoding isn't creating an issue (at least that is my interpretation of ldd).  freelan2 binary should be in /usr/sbin to be FHS-standard compliant (/usr/bin if freelan can be used by ordinary users). I think it would be nice if freelan2 retained the name of simply freelan.

**Comment by ereOn** [comment]
@leggewie Makes sense.

`freelan` can be used by ordinary user : they just won't be allowed to create/configure a tap adapter (but freelan can be used without one, in the case of non-members relays for instance).

I'm gonna change the following things this evening:

* Add a `install_prefix` option to the SCons scripts : `install_prefix` will be the thing that gets hardcoded in the binary such that the package builder can just do :  `scons install prefix=debian/freelan/` install_prefix=/`. The default for `install_prefix` will be to take the same value as `prefix` so that from-source installs can just do : `scons install prefix=/usr/local`.
* Rename the binary from `freelan2` to `freelan`

Would that be enough or is there anything else left to change to ease packaging ?

**Comment by leggewie** [comment]
The freelan binary should reside in /usr/bin, then. Does the program emit a warning when run without sufficient privileges and trying to create/configure a tap adapter?
I tested my Debian packages only briefly but it didn't look like the split into --prefix=debian/freelan/ and --install_prefix=/ was necessary.

**Comment by ereOn** [comment]
@leggewie If the user tries to create a tap adapter but doesn't have the permissions to do so (he doesn't have to be root by the way, he can just have the `CAP_NET_ADMIN` capability), the program stops with a fatal error indicating that the tap adapter could not be created (not just a warning, since in this case FreeLAN cannot possibly reach its goals - it would be pointless to run without a tap adapter when the user explicitely asked for one)

Regarding the `prefix` thing, I'm confused:
- You said [the other day](https://github.com/freelan-developers/freelan-all/issues/59#issuecomment-84823542):

> "The installation path is hardcoded in the binary (via a compilation flag generated for you automatically)" Is that a relative or an absolute path? I don't think either will work, in fact. Debian often builds in a chroot, so the relative installation path would be debian/freelan/, for example, installing to debian/freelan/{etc,usr/sbin}. The binary package will then be installing to /etc and /usr/sbin

Can you describe to me the exact command you'd like to type in the packaging `Makefile` and the effet it should have ?

**Comment by leggewie** [comment]
I was theoreticizing. After doing the actual build I found out that this seemed to work as expected. I think it's safe to drop a1db80e
Moving the binary to /usr/bin sounds like the thing to do.

**Comment by ereOn** [comment]
@leggewie Thanks for testing this !

I just merged those commits (except for https://github.com/freelan-developers/freelan-all/commit/a1db80e967fd691c75a393a11d67827614a618f6) in [`master`](https://github.com/freelan-developers/freelan-all/tree/master).
